[package]
name = "dice_engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
rand_hc = "0.3.1"

[dev-dependencies]
rstest = "0.12.0"
mockall = "0.11.0"