trigger:
- master
- feature/*

pr:
  autoCancel: true
  branches:
    include:
      - master

jobs:
  - job: Build
    pool:
      name: Azure Pipelines
      vmImage: ubuntu-latest
    container: rust:1.60-buster
    workspace:
      clean: all    
    steps:
      - script: cargo install --path .
        displayName: Install dependencies
      - script: cargo build -r                
        displayName: Build app
      - script: cargo test        
        displayName: Test app
      